name: flutter_recruitment_task
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  auto_route: 3.2.4
  easy_localization: 3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_hooks: 0.18.2+1
  freezed_annotation: 1.1.0
  get_it: 7.2.0
  hooked_bloc: 1.0.3
  http: 0.13.4
  injectable: 1.5.3
  json_annotation: 4.4.0

dev_dependencies:
  auto_route_generator: 3.2.3
  build_runner: 2.1.8
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 2.1.2+1
  flutter_test:
    sdk: flutter
  freezed: 1.1.1
  injectable_generator: 1.5.3
  json_serializable: 6.1.5
  retrofit_generator: 4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
